export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const ERROR = 'ERROR';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_ID = 'FETCH_BY_ID';
export const FETCH_BY_PHTGPHR_ID = 'FETCH_BY_PHTGPHR_ID';

export const CREATE_CALENDAR = 'CREATE_CALENDAR';
export const UPDATE_CALENDAR = 'UPDATE_CALENDAR';
export const DELETE_CALENDAR = 'DELETE_CALENDAR';
export const FETCH_ALL_CALENDAR = 'FETCH_ALL_CALENDAR';
export const FETCH_CALENDAR_BY_ID = 'FETCH_CALENDAR_BY_ID';
export const FETCH_CALENDAR_BY_PHTGPHR_ID = 'FETCH_CALENDAR_BY_PHTGPHR_ID';


export const CREATE_PHOTOGRAPHER = 'CREATE_PHOTOGRAPHER';
export const UPDATE_PHOTOGRAPHER = 'UPDATE_PHOTOGRAPHER';
export const DELETE_PHOTOGRAPHER = 'DELETE_PHOTOGRAPHER';
export const FETCH_ALL_PHOTOGRAPHER = 'FETCH_ALL_PHOTOGRAPHER';
export const FETCH_PHOTOGRAPHER_BY_ID = 'FETCH_PHOTOGRAPHER_BY_ID';
export const FETCH_PHOTOGRAPHER_BY_EMAIL = 'FETCH_PHOTOGRAPHER_BY_EMAIL';
export const FETCH_PHOTOGRAPHER_BY_PHTGPHR_ID = 'FETCH_PHOTOGRAPHER_BY_PHTGPHR_ID';

export const CREATE_PACKAGE = 'CREATE_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const FETCH_ALL_PACKAGE = 'FETCH_ALL_PACKAGE';
export const FETCH_PACKAGE_BY_ID = 'FETCH_PACKAGE_BY_ID';
export const FETCH_PACKAGE_BY_PHTGPHR_ID = 'FETCH_PACKAGE_BY_PHTGPHR_ID';

export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const FETCH_ALL_PORTFOLIO = 'FETCH_ALL_PORTFOLIO';
export const FETCH_PORTFOLIO_BY_ID = 'FETCH_PORTFOLIO_BY_ID';
export const FETCH_PORTFOLIO_BY_PHTGPHR_ID = 'FETCH_PORTFOLIO_BY_PHTGPHR_ID';


export const CREATE_BOOKING = 'CREATE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const FETCH_ALL_BOOKING = 'FETCH_ALL_BOOKING';
export const FETCH_BOOKING_BY_ID = 'FETCH_BOOKING_BY_ID';
export const FETCH_BOOKING_BY_PHTGPHR_ID = 'FETCH_BOOKING_BY_PHTGPHR_ID';
export const FETCH_BOOKING_BY_USER_ID = 'FETCH_BOOKING_BY_USER_ID';
export const FETCH_BOOKING_BY_CALENDAR_ID = 'FETCH_BOOKING_BY_CALENDAR_ID';


export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_ALL_USER = 'FETCH_ALL_USER';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const FETCH_USER_BY_EMAIL = 'FETCH_USER_BY_EMAIL';